# H2 in-memory database for testing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=flashlink-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.topics.analytics-events=analytics-events-topic
spring.kafka.topics.analytics-events=dummy-topic



# Server configuration
server.port=8080

# Flashlink configuration
flashlink.node-id=1
